apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyuncc23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyuncc23
  template:
    metadata:
      labels:
        app: kyuncc23
    spec:
      containers:
      - image: okteto.dev/kyuncc23:latest
        name: kyuncc23
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9a879977-ae03-49a0-8aab-efade3ac3eec"
        - name: Vless_Path
          value: "/vl331"
        - name: Vmess_UUID
          value: "9a879977-ae03-49a0-8aab-efade3ac3eec"
        - name: Vmess_Path
          value: "/vm332"
        - name: Share_Path
          value: "/v2link"
