apiVersion: v1
kind: Service
metadata:
  name: kyuncc23
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "kyuncc23"
    port: 8080
  selector:
    app: kyuncc23
